fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  registration:
    form:
      type: App\Form\RegistrationType
  from_email:
    address: "yohav.ruimy@gmail.com"
    sender_name: "yohav.ruimy@gmail.com"